### ISSUE TITLE
Fonts and incorrect symbols

### ISSUE THREAD

**Issue by Salamandar** [eugenk/zsh-prompt-iggy#1]
"Arrow" symbols don't display correctly, even using powerline-patched fonts :(

**Comment by eugenk** [comment]
I'm sorry, but I don't maintain this prompt any more. I just added a deprecation notice to the Readme.md which shows an alternative configuration. As soon as I have some time to spare, I will add some screenshots of the alternative prompt.

**Comment by Salamandar** [comment]
Got it !
